name: badger_site
publish_to: none
dependencies:
  ace: ">=0.6.0+24.2.15 <0.7.0"
  badger:
    git: git://github.com/DirectMyFile/badger.git
  browser: ">=0.10.0+2 <0.11.0"
transformers:
- $dart2js:
    commandLineOptions: ["--enable-experimental-mirrors"]
